runtime: java17
env: standard
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  ACTIVE_PROFILE: prod
  DATABASE_URL: autorack.proxy.rlwy.net:13142
  DATABASE_NAME: railway
  DATABASE_USER: root
  DATABASE_PASSWORD: LBEfaiQOqlAtksqXWzfVbeqWnIdDqtax
  SERVER_PORT: '8080'
  API_KEY: AIzaSyC4-mIS6YajEfklY8AuIpNEFtMbixkQKrw
  BUCKET_ID: projeto-esi-restaurant-carinho-bucket
  GCP_DIR_IMAGES_NAMES: dishimages
