runtime: java17
env: standard
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  ACTIVE_PROFILE: prod
  DATABASE_URL: projeto-esi:southamerica-east1:mysqldb
  DATABASE_NAME: restaurantdb
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  SERVER_PORT: '8080'
  API_KEY: AIzaSyBj7D_d69IKHIDnXEkUdcuZ
  BUCKET_ID: restaurante-carinho-bucket
  GCP_DIR_IMAGES_NAMES: dishimages
